# Generated by Django 4.2.3 on 2023-07-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_create_user', '0002_alter_user_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userinfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting_create_user.userinfo'),
        ),
    ]
