# Generated by Django 4.2.3 on 2023-08-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_create_user', '0003_alter_user_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ImageField(default='', upload_to='')),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(upload_to='your_name_folder')),
            ],
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='alcohol',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
