# Generated by Django 4.2.3 on 2023-08-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_create_user', '0004_usercode_alter_alcohol_alcohol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
