# Generated by Django 4.2.2 on 2023-08-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_between_users', '0002_remove_sender_sender_remove_messages_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='recipient',
        ),
    ]
